pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-nginx-app"
    }

    stages {

        stage('Clone Code') {
            steps {
                echo "Cloning repo..."
                // Jenkins already clones automatically if using SCM
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container') {
            steps {
                echo "Running container..."
                sh '''
                docker stop my-container || true
                docker rm my-container || true
                docker run -d -p 8081:80 --name my-container $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline SUCCESS"
        }
        failure {
            echo "Pipeline FAILED"
        }
    }
}
